#!/usr/bin/env node
/**
 * Generates app/src/main/assets/seed_games.json — the mandatory offline seed set
 * (docs/08-GAME-DATA.md, docs/05-TECH-ARCHITECTURE.md). No live IGDB/Twitch credentials
 * exist yet (docs/09-PENDING-INPUTS.md), so this is hand-curated from real, well-known
 * titles with genre-median playtime estimates rather than pulled from the IGDB API.
 *
 * IDs are negative and sequential specifically so they can never collide with real
 * (positive) IGDB ids once live data starts flowing in — a seed-sourced GameEntity is
 * trivially distinguishable from a cached IGDB one.
 *
 * Regenerate once IGDB/Twitch access is confirmed (docs/09-PENDING-INPUTS.md) by having
 * the Worker call the real `/games/search` pipeline for each title here and overwrite this
 * file with accurate cover URLs, ratings, and IGDB time-to-beat data.
 *
 * Run: node tools/generate_seed.mjs
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(__dirname, "..", "app", "src", "main", "assets", "seed_games.json");

// genre -> [hastily, normally, completely] hours (genre-median estimates, per
// docs/08-GAME-DATA.md's fallback rule: "fall back to a genre-based median estimate and
// mark it as an estimate in the UI" — isEstimate is carried on every seed row).
const GENRE_PLAYTIME = {
  Simulator: [5, 15, 40],
  Puzzle: [3, 6, 10],
  Shooter: [5, 10, 15],
  Fighting: [2, 5, 8],
  Racing: [3, 8, 15],
  "Hack and slash/Beat 'em up": [6, 15, 25],
  Adventure: [8, 15, 30],
  "Role-playing (RPG)": [15, 40, 80],
  "Visual Novel": [5, 12, 20],
  Strategy: [10, 25, 50],
  Tactical: [10, 20, 40],
  Platform: [4, 8, 15],
  Indie: [3, 8, 15],
  "Point-and-click": [4, 8, 12],
  Horror: [5, 8, 12],
  Sport: [3, 10, 20],
};

// [title, year, genre, platforms[]]
const GAMES = [
  // Simulator
  ["The Sims 4", 2014, "Simulator", ["PC", "PlayStation", "Xbox"]],
  ["Stardew Valley", 2016, "Simulator", ["PC", "Switch", "PlayStation", "Xbox"]],
  ["Animal Crossing: New Horizons", 2020, "Simulator", ["Switch"]],
  ["Cities: Skylines", 2015, "Simulator", ["PC", "PlayStation", "Xbox"]],
  ["Planet Coaster", 2016, "Simulator", ["PC", "PlayStation", "Xbox"]],
  ["Microsoft Flight Simulator", 2020, "Simulator", ["PC", "Xbox"]],
  ["Two Point Hospital", 2018, "Simulator", ["PC", "Switch", "PlayStation", "Xbox"]],
  ["Farming Simulator 22", 2021, "Simulator", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["House Flipper", 2018, "Simulator", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["PowerWash Simulator", 2022, "Simulator", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Euro Truck Simulator 2", 2012, "Simulator", ["PC"]],
  ["Kerbal Space Program", 2015, "Simulator", ["PC", "PlayStation", "Xbox"]],
  ["Surgeon Simulator", 2013, "Simulator", ["PC", "PlayStation", "Xbox"]],
  ["Goat Simulator", 2014, "Simulator", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Football Manager 2024", 2023, "Simulator", ["PC", "Switch"]],
  ["RollerCoaster Tycoon 2", 2002, "Simulator", ["PC"]],
  ["SimCity 4", 2003, "Simulator", ["PC"]],
  ["Viva Piñata", 2006, "Simulator", ["Xbox"]],
  ["Harvest Moon: A Wonderful Life", 2003, "Simulator", ["PlayStation"]],
  ["Story of Seasons: Pioneers of Olive Town", 2021, "Simulator", ["Switch", "PC"]],
  ["Coral Island", 2023, "Simulator", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["My Time at Portia", 2019, "Simulator", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Sun Haven", 2023, "Simulator", ["PC", "Switch"]],
  ["Fields of Mistria", 2024, "Simulator", ["PC"]],
  ["Disney Dreamlight Valley", 2022, "Simulator", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Ooblets", 2022, "Simulator", ["PC", "Xbox", "Switch"]],
  ["Spiritfarer", 2020, "Simulator", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Garden Paws", 2019, "Simulator", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Ranch Simulator", 2022, "Simulator", ["PC"]],
  ["Bear and Breakfast", 2022, "Simulator", ["PC", "Xbox", "Switch"]],
  ["Cooking Simulator", 2019, "Simulator", ["PC", "PlayStation", "Xbox"]],
  ["Placid Plastic Duck Simulator", 2022, "Simulator", ["PC", "Switch"]],
  ["Lawn Mowing Simulator", 2021, "Simulator", ["PC", "PlayStation", "Xbox"]],
  ["Thief Simulator", 2018, "Simulator", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Bus Simulator 21", 2021, "Simulator", ["PC", "PlayStation", "Xbox"]],
  ["Tiny Glade", 2024, "Simulator", ["PC"]],

  // Puzzle
  ["Portal 2", 2011, "Puzzle", ["PC", "PlayStation", "Xbox"]],
  ["The Witness", 2016, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Baba Is You", 2019, "Puzzle", ["PC", "Switch", "PlayStation", "Xbox"]],
  ["Tetris Effect", 2018, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Portal", 2007, "Puzzle", ["PC", "Xbox"]],
  ["The Talos Principle", 2014, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Human Resource Machine", 2015, "Puzzle", ["PC", "Switch"]],
  ["Return of the Obra Dinn", 2018, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Superliminal", 2019, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["The Room", 2012, "Puzzle", ["PC", "PlayStation", "Switch"]],
  ["Lumines Remastered", 2018, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Puyo Puyo Tetris 2", 2020, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Antichamber", 2013, "Puzzle", ["PC"]],
  ["The Witness (remaster)", 2021, "Puzzle", ["Switch"]],
  ["World of Goo", 2008, "Puzzle", ["PC", "Switch", "Wii"]],
  ["Braid", 2008, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Fez", 2012, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Inside", 2016, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Limbo", 2010, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Gorogoa", 2017, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Manifold Garden", 2019, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["The Case of the Golden Idol", 2022, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Escape Simulator", 2021, "Puzzle", ["PC"]],
  ["Cocoon", 2023, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Patrick's Parabox", 2022, "Puzzle", ["PC", "Switch"]],
  ["Stephen's Sausage Roll", 2016, "Puzzle", ["PC", "Switch"]],
  ["A Monster's Expedition", 2020, "Puzzle", ["PC", "Switch"]],
  ["Untitled Goose Game", 2019, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["What the Golf?", 2019, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Unpacking", 2021, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Slay the Spire", 2019, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Opus Magnum", 2017, "Puzzle", ["PC"]],
  ["Cube Escape Collection", 2018, "Puzzle", ["PC", "Switch"]],
  ["Chants of Sennaar", 2023, "Puzzle", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Blue Prince", 2025, "Puzzle", ["PC", "PlayStation"]],

  // Shooter
  ["Doom Eternal", 2020, "Shooter", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Call of Duty: Modern Warfare II", 2022, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Titanfall 2", 2016, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Halo Infinite", 2021, "Shooter", ["PC", "Xbox"]],
  ["Apex Legends", 2019, "Shooter", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Overwatch 2", 2022, "Shooter", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Destiny 2", 2017, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Valorant", 2020, "Shooter", ["PC"]],
  ["Counter-Strike 2", 2023, "Shooter", ["PC"]],
  ["Borderlands 3", 2019, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Metro Exodus", 2019, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Wolfenstein: The New Order", 2014, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Bioshock Infinite", 2013, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Half-Life 2", 2004, "Shooter", ["PC", "Xbox"]],
  ["Half-Life: Alyx", 2020, "Shooter", ["PC"]],
  ["Left 4 Dead 2", 2009, "Shooter", ["PC", "Xbox"]],
  ["Splitgate", 2021, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Deep Rock Galactic", 2020, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Helldivers 2", 2024, "Shooter", ["PC", "PlayStation"]],
  ["The Finals", 2023, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Warframe", 2013, "Shooter", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Rainbow Six Siege", 2015, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Battlefield 1", 2016, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Sniper Elite 5", 2022, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Remnant II", 2023, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Control", 2019, "Shooter", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Star Wars Jedi: Survivor", 2023, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Ready or Not", 2023, "Shooter", ["PC"]],
  ["Escape from Tarkov", 2017, "Shooter", ["PC"]],
  ["Payday 2", 2013, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Team Fortress 2", 2007, "Shooter", ["PC"]],
  ["Doom (2016)", 2016, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Far Cry 5", 2018, "Shooter", ["PC", "PlayStation", "Xbox"]],
  ["Gears 5", 2019, "Shooter", ["PC", "Xbox"]],
  ["Metal Gear Solid V: The Phantom Pain", 2015, "Shooter", ["PC", "PlayStation", "Xbox"]],

  // Fighting
  ["Street Fighter 6", 2023, "Fighting", ["PC", "PlayStation", "Xbox"]],
  ["Tekken 8", 2024, "Fighting", ["PC", "PlayStation", "Xbox"]],
  ["Guilty Gear Strive", 2021, "Fighting", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Super Smash Bros. Ultimate", 2018, "Fighting", ["Switch"]],
  ["Mortal Kombat 1", 2023, "Fighting", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Dragon Ball FighterZ", 2018, "Fighting", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Granblue Fantasy Versus", 2020, "Fighting", ["PC", "PlayStation"]],
  ["Skullgirls", 2012, "Fighting", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["For Honor", 2017, "Fighting", ["PC", "PlayStation", "Xbox"]],
  ["Brawlhalla", 2017, "Fighting", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Under Night In-Birth", 2014, "Fighting", ["PC", "PlayStation", "Switch"]],
  ["The King of Fighters XV", 2022, "Fighting", ["PC", "PlayStation", "Xbox"]],
  ["Multiversus", 2024, "Fighting", ["PC", "PlayStation", "Xbox"]],
  ["Naruto Ultimate Ninja Storm 4", 2016, "Fighting", ["PC", "PlayStation", "Xbox"]],
  ["Injustice 2", 2017, "Fighting", ["PC", "PlayStation", "Xbox"]],
  ["Soulcalibur VI", 2018, "Fighting", ["PC", "PlayStation", "Xbox"]],
  ["Melty Blood: Type Lumina", 2021, "Fighting", ["PC", "PlayStation", "Switch"]],
  ["Them's Fightin' Herds", 2020, "Fighting", ["PC", "PlayStation", "Switch"]],
  ["Rivals of Aether", 2017, "Fighting", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Def Jam: Fight for NY", 2004, "Fighting", ["PlayStation", "Xbox"]],
  ["Yu-Gi-Oh! (arcade lineage - Power of Chaos)", 2004, "Fighting", ["PC"]],
  ["Killer Instinct", 2013, "Fighting", ["PC", "Xbox"]],
  ["Nickelodeon All-Star Brawl 2", 2023, "Fighting", ["PC", "PlayStation", "Xbox", "Switch"]],

  // Racing
  ["Forza Horizon 5", 2021, "Racing", ["PC", "Xbox"]],
  ["Gran Turismo 7", 2022, "Racing", ["PlayStation"]],
  ["Mario Kart 8 Deluxe", 2017, "Racing", ["Switch"]],
  ["F1 24", 2024, "Racing", ["PC", "PlayStation", "Xbox"]],
  ["Need for Speed Heat", 2019, "Racing", ["PC", "PlayStation", "Xbox"]],
  ["Rocket League", 2015, "Racing", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Trackmania", 2020, "Racing", ["PC"]],
  ["Wreckfest", 2018, "Racing", ["PC", "PlayStation", "Xbox"]],
  ["Dirt Rally 2.0", 2019, "Racing", ["PC", "PlayStation", "Xbox"]],
  ["Burnout Paradise Remastered", 2018, "Racing", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Assetto Corsa Competizione", 2019, "Racing", ["PC", "PlayStation", "Xbox"]],
  ["Crash Team Racing Nitro-Fueled", 2019, "Racing", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Hot Wheels Unleashed", 2021, "Racing", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Riders Republic", 2021, "Racing", ["PC", "PlayStation", "Xbox"]],
  ["Art of Rally", 2020, "Racing", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Descenders", 2018, "Racing", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Micro Machines World Series", 2017, "Racing", ["PC", "PlayStation", "Xbox"]],
  ["Sonic Racing: CrossWorlds", 2025, "Racing", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Distance", 2018, "Racing", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Redout 2", 2022, "Racing", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Horizon Chase Turbo", 2018, "Racing", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["The Crew Motorfest", 2023, "Racing", ["PC", "PlayStation", "Xbox"]],

  // Hack and slash
  ["Devil May Cry 5", 2019, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox"]],
  ["Bayonetta", 2009, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["God of War", 2018, "Hack and slash/Beat 'em up", ["PC", "PlayStation"]],
  ["God of War Ragnarök", 2022, "Hack and slash/Beat 'em up", ["PC", "PlayStation"]],
  ["Hades", 2020, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Hades II", 2024, "Hack and slash/Beat 'em up", ["PC"]],
  ["Nioh 2", 2020, "Hack and slash/Beat 'em up", ["PC", "PlayStation"]],
  ["Diablo IV", 2023, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox"]],
  ["Vampire Survivors", 2022, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Warhammer: Vermintide 2", 2018, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox"]],
  ["Streets of Rage 4", 2020, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Dynasty Warriors 9", 2018, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox"]],
  ["Ghostrunner", 2020, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Katana Zero", 2019, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Metal: Hellsinger", 2022, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox"]],
  ["Darksiders III", 2018, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox"]],
  ["Sifu", 2022, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Hi-Fi Rush", 2023, "Hack and slash/Beat 'em up", ["PC", "Xbox"]],
  ["Astral Chain", 2019, "Hack and slash/Beat 'em up", ["Switch"]],
  ["Scarlet Nexus", 2021, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox"]],
  ["Wanted: Dead", 2023, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox"]],
  ["Vanquish", 2010, "Hack and slash/Beat 'em up", ["PC", "PlayStation", "Xbox"]],

  // Adventure
  ["The Legend of Zelda: Breath of the Wild", 2017, "Adventure", ["Switch"]],
  ["The Legend of Zelda: Tears of the Kingdom", 2023, "Adventure", ["Switch"]],
  ["Red Dead Redemption 2", 2018, "Adventure", ["PC", "PlayStation", "Xbox"]],
  ["Uncharted 4: A Thief's End", 2016, "Adventure", ["PlayStation"]],
  ["Tomb Raider (2013)", 2013, "Adventure", ["PC", "PlayStation", "Xbox"]],
  ["Horizon Zero Dawn", 2017, "Adventure", ["PC", "PlayStation"]],
  ["Horizon Forbidden West", 2022, "Adventure", ["PC", "PlayStation"]],
  ["The Last of Us Part I", 2013, "Adventure", ["PC", "PlayStation"]],
  ["Ghost of Tsushima", 2020, "Adventure", ["PC", "PlayStation"]],
  ["Grand Theft Auto V", 2013, "Adventure", ["PC", "PlayStation", "Xbox"]],
  ["Death Stranding", 2019, "Adventure", ["PC", "PlayStation"]],
  ["Sea of Thieves", 2018, "Adventure", ["PC", "Xbox"]],
  ["A Short Hike", 2019, "Adventure", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Journey", 2012, "Adventure", ["PC", "PlayStation"]],
  ["Firewatch", 2016, "Adventure", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["What Remains of Edith Finch", 2017, "Adventure", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Outer Wilds", 2019, "Adventure", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Subnautica", 2018, "Adventure", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["No Man's Sky", 2016, "Adventure", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Assassin's Creed Valhalla", 2020, "Adventure", ["PC", "PlayStation", "Xbox"]],
  ["Days Gone", 2019, "Adventure", ["PC", "PlayStation"]],
  ["Sable", 2021, "Adventure", ["PC", "PlayStation", "Xbox"]],
  ["Genshin Impact", 2020, "Adventure", ["PC", "PlayStation", "Switch"]],
  ["It Takes Two", 2021, "Adventure", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["A Way Out", 2018, "Adventure", ["PC", "PlayStation", "Xbox"]],
  ["Kena: Bridge of Spirits", 2021, "Adventure", ["PC", "PlayStation"]],
  ["Death's Door", 2021, "Adventure", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Tunic", 2022, "Adventure", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Pentiment", 2022, "Adventure", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Botany Manor", 2024, "Adventure", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Firewatch 2 placeholder", 2026, "Adventure", ["PC"]],
  ["The Legend of Zelda: Wind Waker", 2002, "Adventure", ["GameCube"]],
  ["Ico", 2001, "Adventure", ["PlayStation"]],
  ["Shadow of the Colossus", 2005, "Adventure", ["PlayStation"]],

  // RPG
  ["The Witcher 3: Wild Hunt", 2015, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Baldur's Gate 3", 2023, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Elden Ring", 2022, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Persona 5 Royal", 2019, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Final Fantasy VII Remake", 2020, "Role-playing (RPG)", ["PC", "PlayStation"]],
  ["Final Fantasy XIV", 2013, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Dark Souls III", 2016, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Dragon Age: Inquisition", 2014, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Mass Effect Legendary Edition", 2021, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Fallout: New Vegas", 2010, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Fallout 4", 2015, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["The Elder Scrolls V: Skyrim", 2011, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Divinity: Original Sin 2", 2017, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Disco Elysium", 2019, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Pillars of Eternity", 2015, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Xenoblade Chronicles 3", 2022, "Role-playing (RPG)", ["Switch"]],
  ["Pokémon Scarlet", 2022, "Role-playing (RPG)", ["Switch"]],
  ["Octopath Traveler", 2018, "Role-playing (RPG)", ["PC", "Switch"]],
  ["Yakuza: Like a Dragon", 2020, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Nier: Automata", 2017, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Kingdom Come: Deliverance", 2018, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Monster Hunter: World", 2018, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Monster Hunter Wilds", 2025, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Chrono Trigger", 1995, "Role-playing (RPG)", ["PC", "Switch"]],
  ["Undertale", 2015, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Deltarune", 2018, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Diablo II: Resurrected", 2021, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Path of Exile", 2013, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Path of Exile 2", 2024, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Cyberpunk 2077", 2020, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Mass Effect 2", 2010, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Fable Anniversary", 2014, "Role-playing (RPG)", ["PC", "Xbox"]],
  ["Dragon's Dogma 2", 2024, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Lies of P", 2023, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Sekiro: Shadows Die Twice", 2019, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],
  ["Bloodborne", 2015, "Role-playing (RPG)", ["PlayStation"]],
  ["Dark Souls: Remastered", 2018, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Hollow Knight", 2017, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Hollow Knight: Silksong", 2026, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Star Wars: Knights of the Old Republic", 2003, "Role-playing (RPG)", ["PC", "Xbox", "Switch"]],
  ["Final Fantasy X", 2001, "Role-playing (RPG)", ["PlayStation", "PC", "Switch"]],
  ["Final Fantasy XVI", 2023, "Role-playing (RPG)", ["PlayStation", "PC"]],
  ["Granblue Fantasy: Relink", 2024, "Role-playing (RPG)", ["PC", "PlayStation"]],
  ["Tales of Arise", 2021, "Role-playing (RPG)", ["PC", "PlayStation", "Xbox"]],

  // Visual Novel
  ["Doki Doki Literature Club", 2017, "Visual Novel", ["PC", "PlayStation", "Switch"]],
  ["Steins;Gate", 2009, "Visual Novel", ["PC", "PlayStation", "Switch"]],
  ["Danganronpa: Trigger Happy Havoc", 2010, "Visual Novel", ["PC", "PlayStation", "Switch"]],
  ["Zero Escape: Virtue's Last Reward", 2012, "Visual Novel", ["PC", "PlayStation", "Switch"]],
  ["Ace Attorney Trilogy", 2019, "Visual Novel", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Coffee Talk", 2020, "Visual Novel", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["AI: The Somnium Files", 2019, "Visual Novel", ["PC", "PlayStation", "Switch"]],
  ["Umineko When They Cry", 2007, "Visual Novel", ["PC", "Switch"]],
  ["Fate/Stay Night", 2004, "Visual Novel", ["PC", "PlayStation"]],
  ["Higurashi When They Cry", 2002, "Visual Novel", ["PC", "Switch"]],
  ["The House in Fata Morgana", 2012, "Visual Novel", ["PC", "PlayStation", "Switch"]],
  ["Root Letter", 2016, "Visual Novel", ["PC", "PlayStation", "Switch"]],
  ["VA-11 Hall-A", 2016, "Visual Novel", ["PC", "PlayStation", "Switch"]],
  ["Butterfly Soup", 2017, "Visual Novel", ["PC"]],
  ["Ladykiller in a Bind", 2016, "Visual Novel", ["PC"]],
  ["Long Live the Queen", 2012, "Visual Novel", ["PC"]],
  ["A Space for the Unbound", 2023, "Visual Novel", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Slay the Princess", 2023, "Visual Novel", ["PC"]],
  ["Needy Streamer Overload", 2022, "Visual Novel", ["PC", "Switch"]],
  ["World's End Club", 2021, "Visual Novel", ["PC", "Switch"]],

  // Strategy
  ["Civilization VI", 2016, "Strategy", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Civilization VII", 2025, "Strategy", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Age of Empires IV", 2021, "Strategy", ["PC"]],
  ["StarCraft II", 2010, "Strategy", ["PC"]],
  ["Total War: Warhammer III", 2022, "Strategy", ["PC"]],
  ["Crusader Kings III", 2020, "Strategy", ["PC", "PlayStation", "Xbox"]],
  ["Europa Universalis IV", 2013, "Strategy", ["PC"]],
  ["Stellaris", 2016, "Strategy", ["PC", "PlayStation", "Xbox"]],
  ["Company of Heroes 3", 2023, "Strategy", ["PC"]],
  ["XCOM 2", 2016, "Strategy", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Frostpunk", 2018, "Strategy", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Frostpunk 2", 2024, "Strategy", ["PC"]],
  ["They Are Billions", 2019, "Strategy", ["PC", "PlayStation", "Xbox"]],
  ["Anno 1800", 2019, "Strategy", ["PC", "PlayStation", "Xbox"]],
  ["Homeworld 3", 2024, "Strategy", ["PC"]],
  ["Age of Mythology: Retold", 2024, "Strategy", ["PC"]],
  ["Northgard", 2018, "Strategy", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Battle Brothers", 2017, "Strategy", ["PC", "Switch"]],
  ["Wargroove", 2019, "Strategy", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Advance Wars 1+2: Re-Boot Camp", 2023, "Strategy", ["Switch"]],
  ["Terra Invicta", 2023, "Strategy", ["PC"]],
  ["Total War: Three Kingdoms", 2019, "Strategy", ["PC"]],
  ["Command & Conquer: Red Alert 2", 2000, "Strategy", ["PC"]],
  ["Warcraft III: Reforged", 2020, "Strategy", ["PC"]],
  ["Endless Space 2", 2017, "Strategy", ["PC"]],
  ["Offworld Trading Company", 2016, "Strategy", ["PC"]],

  // Tactical
  ["Into the Breach", 2018, "Tactical", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Fire Emblem: Three Houses", 2019, "Tactical", ["Switch"]],
  ["Fire Emblem Engage", 2023, "Tactical", ["Switch"]],
  ["Divinity: Original Sin", 2014, "Tactical", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Wasteland 3", 2020, "Tactical", ["PC", "PlayStation", "Xbox"]],
  ["Mario + Rabbids Kingdom Battle", 2017, "Tactical", ["Switch"]],
  ["Gears Tactics", 2020, "Tactical", ["PC", "Xbox"]],
  ["Tactics Ogre: Reborn", 2022, "Tactical", ["PC", "PlayStation", "Switch"]],
  ["Final Fantasy Tactics", 1997, "Tactical", ["PlayStation"]],
  ["Triangle Strategy", 2022, "Tactical", ["Switch"]],
  ["Phantom Brave", 2004, "Tactical", ["PlayStation", "PC"]],
  ["Disgaea 7", 2023, "Tactical", ["PC", "PlayStation", "Switch"]],
  ["Banner Saga", 2014, "Tactical", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Jagged Alliance 3", 2023, "Tactical", ["PC"]],
  ["The Last Spell", 2023, "Tactical", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Ash of Gods: Redemption", 2018, "Tactical", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Symphony of War", 2022, "Tactical", ["PC", "Switch"]],
  ["Ratings placeholder Wartales", 2023, "Tactical", ["PC", "PlayStation", "Xbox"]],

  // Platform
  ["Super Mario Odyssey", 2017, "Platform", ["Switch"]],
  ["Super Mario Bros. Wonder", 2023, "Platform", ["Switch"]],
  ["Celeste", 2018, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Hollow Knight (platform tag)", 2017, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Rayman Legends", 2013, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Ori and the Blind Forest", 2015, "Platform", ["PC", "Xbox", "Switch"]],
  ["Ori and the Will of the Wisps", 2020, "Platform", ["PC", "Xbox", "Switch"]],
  ["Cuphead", 2017, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Donkey Kong Country: Tropical Freeze", 2014, "Platform", ["Switch"]],
  ["A Hat in Time", 2017, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Shovel Knight", 2014, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Spelunky 2", 2020, "Platform", ["PC", "PlayStation"]],
  ["Dead Cells", 2018, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Rain World", 2017, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Prince of Persia: The Lost Crown", 2024, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Astro's Playroom", 2020, "Platform", ["PlayStation"]],
  ["Astro Bot", 2024, "Platform", ["PlayStation"]],
  ["Kirby and the Forgotten Land", 2022, "Platform", ["Switch"]],
  ["Sonic Frontiers", 2022, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Crash Bandicoot 4", 2020, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Psychonauts 2", 2021, "Platform", ["PC", "PlayStation", "Xbox"]],
  ["Ratchet & Clank: Rift Apart", 2021, "Platform", ["PC", "PlayStation"]],
  ["Little Nightmares II", 2021, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Yoshi's Crafted World", 2019, "Platform", ["Switch"]],
  ["Klonoa Phantasy Reverie Series", 2022, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Blasphemous", 2019, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Blasphemous 2", 2023, "Platform", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Guacamelee 2", 2018, "Platform", ["PC", "PlayStation", "Switch"]],

  // Indie
  ["Among Us", 2018, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Papers, Please", 2013, "Indie", ["PC", "PlayStation", "Switch"]],
  ["Terraria", 2011, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["FTL: Faster Than Light", 2012, "Indie", ["PC", "Switch"]],
  ["Cult of the Lamb", 2022, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Signalis", 2022, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Balatro", 2024, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Inscryption", 2021, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Cassette Beasts", 2023, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Neon White", 2022, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Rift Wizard", 2020, "Indie", ["PC"]],
  ["Loop Hero", 2021, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Wildermyth", 2021, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Moonlighter", 2018, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Graveyard Keeper", 2018, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Turnip Boy Commits Tax Evasion", 2021, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Chicory: A Colorful Tale", 2021, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Wizard of Legend", 2018, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Overcooked! 2", 2018, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Golf With Your Friends", 2020, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Lethal Company", 2023, "Indie", ["PC"]],
  ["Content Warning", 2024, "Indie", ["PC"]],
  ["Vampire Survivors: Legacy of the Moonspell", 2023, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Astroneer", 2019, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["The Forest", 2018, "Indie", ["PC", "PlayStation"]],
  ["Sons of the Forest", 2024, "Indie", ["PC"]],
  ["Muck", 2021, "Indie", ["PC"]],
  ["Core Keeper", 2022, "Indie", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["V Rising", 2022, "Indie", ["PC", "PlayStation", "Xbox"]],
  ["Raft", 2022, "Indie", ["PC", "PlayStation", "Xbox"]],
  ["Groundhog Day-like Deathloop tag", 2021, "Indie", ["PC", "PlayStation"]],

  // Point-and-click
  ["Grim Fandango Remastered", 1998, "Point-and-click", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Broken Sword: Shadow of the Templars", 1996, "Point-and-click", ["PC", "Switch"]],
  ["The Secret of Monkey Island", 1990, "Point-and-click", ["PC", "Switch"]],
  ["Day of the Tentacle Remastered", 1993, "Point-and-click", ["PC", "PlayStation", "Switch"]],
  ["Sam & Max Save the World", 2006, "Point-and-click", ["PC", "PlayStation", "Switch"]],
  ["Thimbleweed Park", 2017, "Point-and-click", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["The Wolf Among Us", 2013, "Point-and-click", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Life Is Strange", 2015, "Point-and-click", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Detroit: Become Human", 2018, "Point-and-click", ["PC", "PlayStation"]],
  ["Kentucky Route Zero", 2020, "Point-and-click", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Oxenfree", 2016, "Point-and-click", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Disco Elysium (pnc tag)", 2019, "Point-and-click", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["The Longing", 2020, "Point-and-click", ["PC"]],
  ["Norco", 2022, "Point-and-click", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Backbone", 2021, "Point-and-click", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Unavowed", 2018, "Point-and-click", ["PC"]],
  ["Return to Monkey Island", 2022, "Point-and-click", ["PC", "Switch"]],

  // Horror
  ["Resident Evil 4 (2023)", 2023, "Horror", ["PC", "PlayStation", "Xbox"]],
  ["Resident Evil Village", 2021, "Horror", ["PC", "PlayStation", "Xbox"]],
  ["Silent Hill 2 (2024)", 2024, "Horror", ["PC", "PlayStation"]],
  ["Alien: Isolation", 2014, "Horror", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Outlast", 2013, "Horror", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Amnesia: The Dark Descent", 2010, "Horror", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Amnesia: The Bunker", 2023, "Horror", ["PC", "PlayStation", "Xbox"]],
  ["Dead Space (2023)", 2023, "Horror", ["PC", "PlayStation", "Xbox"]],
  ["Phasmophobia", 2020, "Horror", ["PC"]],
  ["Five Nights at Freddy's", 2014, "Horror", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Little Hope (Dark Pictures)", 2020, "Horror", ["PC", "PlayStation", "Xbox"]],
  ["Layers of Fear", 2016, "Horror", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Visage", 2020, "Horror", ["PC", "PlayStation", "Xbox"]],
  ["The Mortuary Assistant", 2022, "Horror", ["PC", "PlayStation", "Xbox"]],
  ["Devour", 2020, "Horror", ["PC"]],
  ["Fatal Frame: Maiden of Black Water", 2015, "Horror", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Soma", 2015, "Horror", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Inside the Backrooms", 2022, "Horror", ["PC"]],
  ["Cry of Fear", 2013, "Horror", ["PC"]],
  ["Until Dawn", 2015, "Horror", ["PlayStation", "PC"]],

  // Sport
  ["EA Sports FC 24", 2023, "Sport", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["NBA 2K24", 2023, "Sport", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Madden NFL 24", 2023, "Sport", ["PC", "PlayStation", "Xbox"]],
  ["Tony Hawk's Pro Skater 1+2", 2020, "Sport", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Rocket League (sport tag)", 2015, "Sport", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Mario Golf: Super Rush", 2021, "Sport", ["Switch"]],
  ["Mario Tennis Aces", 2018, "Sport", ["Switch"]],
  ["Wii Sports", 2006, "Sport", ["Wii"]],
  ["PGA Tour 2K23", 2022, "Sport", ["PC", "PlayStation", "Xbox"]],
  ["Skate 3", 2010, "Sport", ["PlayStation", "Xbox"]],
  ["WWE 2K24", 2024, "Sport", ["PC", "PlayStation", "Xbox"]],
  ["Olympic Games Tokyo 2020", 2021, "Sport", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Super Mega Baseball 4", 2023, "Sport", ["PC", "PlayStation", "Xbox", "Switch"]],
  ["Golf It!", 2017, "Sport", ["PC"]],
  ["Sports Story", 2024, "Sport", ["Switch"]],
];

const now = Date.now();
const platformsAll = new Set();

const seedGames = GAMES.map(([name, year, genre, platforms], index) => {
  const id = -(index + 1); // negative = seed-sourced, never collides with a real IGDB id
  const [hastily, normally, completely] = GENRE_PLAYTIME[genre] ?? [6, 12, 24];
  platforms.forEach((p) => platformsAll.add(p));
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  return {
    id,
    slug,
    name,
    coverUrl: null,
    backgroundUrl: null,
    released: `${year}-01-01`,
    metacritic: null,
    rating: null,
    playtimeHoursHastily: hastily,
    playtimeHoursNormally: normally,
    playtimeHoursCompletely: completely,
    isEstimatedPlaytime: true,
    genres: [genre],
    tags: [],
    platforms,
    cachedAt: now,
  };
});

writeFileSync(OUT_PATH, JSON.stringify(seedGames, null, 2) + "\n");
console.log(`Wrote ${seedGames.length} games to ${OUT_PATH}`);
console.log(`Genres: ${[...new Set(GAMES.map((g) => g[2]))].join(", ")}`);
