"""
Generates every sound effect and music track CONTINUE? ships, from nothing but maths.

Why synthesise instead of downloading a pack: docs/03-DESIGN-SYSTEM.md §6 requires audio that is
"original or CC0 with a documented licence", and the demo-video rules ban unlicensed audio. A
file this script writes has no upstream licence to track, no attribution to keep in sync, and
can be regenerated byte-for-byte by anyone reading the public repo. The output is dedicated to
the public domain under CC0 1.0 (see docs/AUDIO-LICENSE.md).

    pip install numpy scipy soundfile
    python tools/make_audio.py            # writes app/src/main/res/raw/{sfx,music}_*.ogg

Three music packs (ARCADE, AFTER HOURS, NEON DRIVE) of four tracks each, plus 14 effects.

Everything is deterministic (fixed noise seed), mono, 44.1 kHz, Ogg Vorbis — the one compressed
format both SoundPool and MediaPlayer decode on every API level the app supports (minSdk 26).
"""

from __future__ import annotations

import pathlib

import numpy as np
import soundfile as sf
from scipy.signal import butter, lfilter

SR = 44_100
OUT = pathlib.Path(__file__).resolve().parent.parent / "app" / "src" / "main" / "res" / "raw"
RNG = np.random.default_rng(0xC0FFEE)

# ───────────────────────────── primitives ─────────────────────────────

NOTE_INDEX = {"C": 0, "C#": 1, "D": 2, "D#": 3, "E": 4, "F": 5, "F#": 6, "G": 7, "G#": 8,
              "A": 9, "A#": 10, "B": 11, "Db": 1, "Eb": 3, "Gb": 6, "Ab": 8, "Bb": 10}


def hz(note: str) -> float:
    """'A4' -> 440.0, 'C#5' -> 554.37."""
    name, octave = note[:-1], int(note[-1])
    midi = 12 * (octave + 1) + NOTE_INDEX[name]
    return 440.0 * 2 ** ((midi - 69) / 12)


def samples(seconds: float) -> int:
    return max(1, int(round(seconds * SR)))


def _polyblep(t: np.ndarray, dt: np.ndarray) -> np.ndarray:
    """Band-limits a hard edge so high notes don't alias into a harsh fizz."""
    out = np.zeros_like(t)
    lo = t < dt
    x = t[lo] / dt[lo]
    out[lo] = 2 * x - x * x - 1
    hi = t > 1 - dt
    x = (t[hi] - 1) / dt[hi]
    out[hi] = x * x + 2 * x + 1
    return out


def phase(freq, n: int) -> tuple[np.ndarray, np.ndarray]:
    f = np.broadcast_to(np.asarray(freq, dtype=float), (n,))
    dt = f / SR
    return np.cumsum(dt) % 1.0, dt


def square(freq, n: int, duty: float = 0.5) -> np.ndarray:
    t, dt = phase(freq, n)
    out = np.where(t < duty, 1.0, -1.0)
    out += _polyblep(t, dt)
    out -= _polyblep((t - duty) % 1.0, dt)
    return out


def triangle(freq, n: int) -> np.ndarray:
    t, _ = phase(freq, n)
    return 4 * np.abs(t - 0.5) - 1


def sine(freq, n: int) -> np.ndarray:
    t, _ = phase(freq, n)
    return np.sin(2 * np.pi * t)


def noise(n: int) -> np.ndarray:
    return RNG.uniform(-1, 1, n)


def env(n: int, attack=0.005, decay=0.0, sustain=1.0, release=0.02) -> np.ndarray:
    """ADSR where the note's length *includes* the release, so notes never overhang their slot."""
    a, d, r = samples(attack), samples(decay), samples(release)
    s = max(0, n - a - d - r)
    e = np.concatenate([
        np.linspace(0, 1, a, endpoint=False),
        np.linspace(1, sustain, d, endpoint=False),
        np.full(s, sustain),
        np.linspace(sustain, 0, r),
    ])
    return np.pad(e, (0, max(0, n - len(e))))[:n]


def exp_decay(n: int, seconds: float) -> np.ndarray:
    return np.exp(-np.arange(n) / (seconds * SR))


def lowpass(x: np.ndarray, cutoff: float, order: int = 2) -> np.ndarray:
    b, a = butter(order, cutoff / (SR / 2), btype="low")
    return lfilter(b, a, x)


def highpass(x: np.ndarray, cutoff: float, order: int = 2) -> np.ndarray:
    b, a = butter(order, cutoff / (SR / 2), btype="high")
    return lfilter(b, a, x)


def bandpass(x: np.ndarray, lo: float, hi: float, order: int = 2) -> np.ndarray:
    b, a = butter(order, [lo / (SR / 2), hi / (SR / 2)], btype="band")
    return lfilter(b, a, x)


def echo(x: np.ndarray, delay: float, feedback: float, tail: float = 0.0) -> np.ndarray:
    d = samples(delay)
    y = np.pad(x, (0, samples(tail)))
    den = np.zeros(d + 1)
    den[0], den[d] = 1.0, -feedback
    return lfilter([1.0], den, y)


def room(x: np.ndarray, mix: float = 0.18, tail: float = 0.6) -> np.ndarray:
    """A small Schroeder-style room: four parallel combs, softened. Just enough air."""
    y = np.pad(x, (0, samples(tail)))
    wet = np.zeros_like(y)
    for delay_ms, fb in ((29.7, 0.72), (37.1, 0.70), (41.1, 0.68), (43.7, 0.66)):
        d = samples(delay_ms / 1000)
        den = np.zeros(d + 1)
        den[0], den[d] = 1.0, -fb
        wet += lfilter([1.0], den, y)
    wet = lowpass(wet / 4, 4500)
    return y * (1 - mix) + wet * mix


def place(buf: np.ndarray, sound: np.ndarray, at: float, wrap: bool = False) -> None:
    """Mixes [sound] into [buf] at [at] seconds. With [wrap], a tail past the end loops round."""
    start = samples(at) if at > 0 else 0
    end = start + len(sound)
    if end <= len(buf):
        buf[start:end] += sound
    elif wrap:
        head = len(buf) - start
        buf[start:] += sound[:head]
        rest = sound[head:]
        while len(rest):
            chunk = rest[: len(buf)]
            buf[: len(chunk)] += chunk
            rest = rest[len(chunk):]
    else:
        buf[start:] += sound[: len(buf) - start]


def finish(x: np.ndarray, peak: float = 0.8, fade_in: float = 0.002, fade_out: float = 0.01) -> np.ndarray:
    x = np.tanh(x * 1.1) / np.tanh(1.1)  # gentle glue, never a hard clip
    x = x - np.mean(x)
    fi, fo = samples(fade_in), samples(fade_out)
    x[:fi] *= np.linspace(0, 1, fi)
    x[-fo:] *= np.linspace(1, 0, fo)
    m = np.max(np.abs(x))
    return x * (peak / m) if m > 0 else x


def write(name: str, x: np.ndarray) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / f"{name}.ogg"
    # Written in blocks: libsndfile's Vorbis encoder hangs when handed a long file in one call.
    data = x.astype(np.float32)
    with sf.SoundFile(path, "w", SR, 1, format="OGG", subtype="VORBIS") as f:
        for i in range(0, len(data), 4096):
            f.write(data[i:i + 4096])
    print(f"{path.name:28s} {len(x) / SR:6.2f}s {path.stat().st_size / 1024:7.1f} KB")


# ───────────────────────────── instruments ─────────────────────────────

def pulse_note(note: str, seconds: float, duty=0.5, vol=1.0, vibrato=0.0, attack=0.004,
               release=0.03, decay=0.08, sustain=0.7) -> np.ndarray:
    n = samples(seconds)
    f = hz(note)
    if vibrato:
        t = np.arange(n) / SR
        # Vibrato fades in, the way a player leans into a held note.
        depth = vibrato * np.clip(t / 0.25, 0, 1)
        f = f * (1 + depth * np.sin(2 * np.pi * 5.5 * t))
    return square(f, n, duty) * env(n, attack, decay, sustain, release) * vol


def tri_note(note: str, seconds: float, vol=1.0, release=0.02) -> np.ndarray:
    n = samples(seconds)
    return triangle(hz(note), n) * env(n, 0.003, 0.0, 1.0, release) * vol


def kick(vol=1.0) -> np.ndarray:
    n = samples(0.18)
    f = 45 + 110 * np.exp(-np.arange(n) / (0.03 * SR))
    click = highpass(noise(n), 2000) * exp_decay(n, 0.004) * 0.3
    return (sine(f, n) * exp_decay(n, 0.07) + click) * vol


def snare(vol=1.0) -> np.ndarray:
    n = samples(0.16)
    body = triangle(190, n) * exp_decay(n, 0.03) * 0.5
    rattle = bandpass(noise(n), 1500, 9000) * exp_decay(n, 0.05)
    return (body + rattle) * vol


def hat(vol=1.0, open_=False) -> np.ndarray:
    """Half the level of the first build: the first listen called the arcade pack "lots of
    high-pitch noise", and most of that was hats."""
    n = samples(0.18 if open_ else 0.04)
    return highpass(noise(n), 7000) * exp_decay(n, 0.06 if open_ else 0.012) * vol * 0.5


def crash(vol=1.0) -> np.ndarray:
    n = samples(1.6)
    return highpass(noise(n), 4000) * exp_decay(n, 0.45) * vol


# ───────────────────────────── sequencer ─────────────────────────────

class Track:
    """A beat-addressed mix bus. Loops wrap their tails so the seam is inaudible."""

    def __init__(self, bpm: float, beats: float, loop: bool):
        self.spb = 60.0 / bpm
        self.loop = loop
        self.buf = np.zeros(samples(beats * self.spb) + (0 if loop else samples(3.0)))

    def add(self, beat: float, sound: np.ndarray) -> None:
        place(self.buf, sound, beat * self.spb, wrap=self.loop)

    def seconds(self, beats: float) -> float:
        return beats * self.spb

    def melody(self, start: float, notes, voice) -> float:
        """notes: [(note|None, beats)]. Returns the beat after the phrase."""
        b = start
        for note, length in notes:
            if note is not None:
                self.add(b, voice(note, self.seconds(length)))
            b += length
        return b


CHORDS = {
    "C": ["C", "E", "G"], "Am": ["A", "C", "E"], "F": ["F", "A", "C"], "G": ["G", "B", "D"],
    "Em": ["E", "G", "B"], "Dm": ["D", "F", "A"], "E": ["E", "G#", "B"], "G7": ["G", "B", "F"],
    "Fmaj7": ["F", "A", "E"], "Dm7": ["D", "F", "C"], "Gm7": ["G", "Bb", "F"], "C7": ["C", "E", "Bb"],
    "Bbmaj7": ["Bb", "D", "A"],
}


def arp(track: Track, bar_beat: float, chord: str, octave: int, beats=4, step=0.25, vol=0.16,
        duty=0.125, pattern=(0, 1, 2, 1)) -> None:
    tones = CHORDS[chord]
    i = 0
    b = bar_beat
    while b < bar_beat + beats - 1e-6:
        idx = pattern[i % len(pattern)]
        note = f"{tones[idx % 3]}{octave + idx // 3}"
        track.add(b, pulse_note(note, track.seconds(step) * 0.9, duty=duty, vol=vol,
                                decay=0.05, sustain=0.4, release=0.01))
        b += step
        i += 1


def bass(track: Track, bar_beat: float, root: str, octave=2, beats=4, vol=0.55, style="octave") -> None:
    b = bar_beat
    i = 0
    while b < bar_beat + beats - 1e-6:
        if style == "octave":
            note = f"{root}{octave + (i % 2)}"
            length = 0.5
        else:  # "pulse": driving repeated eighths
            note = f"{root}{octave}"
            length = 0.5
        track.add(b, tri_note(note, track.seconds(length) * 0.92, vol=vol))
        b += length
        i += 1


def drums(track: Track, bar_beat: float, beats=4, kick_on=(0, 2), snare_on=(1, 3), hats=0.5,
          vol=1.0) -> None:
    for k in kick_on:
        track.add(bar_beat + k, kick(0.9 * vol))
    for s in snare_on:
        track.add(bar_beat + s, snare(0.45 * vol))
    if hats:
        b = 0.0
        while b < beats - 1e-6:
            track.add(bar_beat + b, hat(0.22 * vol if b % 1 == 0 else 0.14 * vol))
            b += hats


# ───────────────────────────── sound effects ─────────────────────────────

def sfx_coin() -> np.ndarray:
    """The coin. Two pulse notes a fourth apart — the most recognisable sound in arcades."""
    a = square(hz("B5"), samples(0.075), 0.5) * 0.8
    n = samples(0.42)
    b = square(hz("E6"), n, 0.5) * exp_decay(n, 0.13)
    return finish(room(np.concatenate([a, b]), 0.12, 0.25))


def sfx_coin_drop() -> np.ndarray:
    """A payout: a cascade of coins landing, for a RevenueCat grant arriving."""
    buf = np.zeros(samples(1.4))
    coin = sfx_coin()
    for i, at in enumerate((0.0, 0.09, 0.17, 0.24, 0.30, 0.36, 0.42)):
        pitch = 1 + 0.03 * (i % 3)
        idx = np.clip((np.arange(int(len(coin) / pitch)) * pitch).astype(int), 0, len(coin) - 1)
        place(buf, coin[idx] * (0.9 - i * 0.07), at)
    return finish(buf)


def sfx_lever() -> np.ndarray:
    """A slot-machine lever: ratchet teeth on the way down, then the mechanism bottoming out."""
    buf = np.zeros(samples(0.55))
    for i in range(5):
        n = samples(0.018)
        tick = bandpass(noise(n), 2500, 7000) * exp_decay(n, 0.004) * (0.35 + 0.05 * i)
        place(buf, tick, i * 0.032)
    n = samples(0.35)
    f = 70 * np.exp(-np.arange(n) / (0.12 * SR)) + 42
    thud = sine(f, n) * exp_decay(n, 0.09) * 1.2
    clank = bandpass(noise(n), 400, 2400) * exp_decay(n, 0.025) * 0.6
    metal = (square(hz("D4"), n, 0.3) + square(hz("A4") * 1.01, n, 0.3)) * exp_decay(n, 0.05) * 0.12
    place(buf, thud + clank + metal, 0.17)
    return finish(room(buf, 0.15, 0.3))


def sfx_deal() -> np.ndarray:
    """A card leaving the shoe: a short paper swish whose band sweeps down."""
    n = samples(0.16)
    x = noise(n)
    t = np.arange(n) / n
    lo_band = bandpass(x, 900, 3000) * t
    hi_band = bandpass(x, 3000, 9000) * (1 - t)
    e = env(n, 0.012, 0.03, 0.5, 0.08)
    return finish((lo_band + hi_band) * e)


def sfx_flip() -> np.ndarray:
    """A card turning face up: two tight snaps."""
    buf = np.zeros(samples(0.12))
    for at, v in ((0.0, 0.7), (0.045, 1.0)):
        n = samples(0.03)
        place(buf, bandpass(noise(n), 1800, 8000) * exp_decay(n, 0.006) * v, at)
    return finish(buf)


def sfx_whoosh() -> np.ndarray:
    """A card flung away (SKIP / NOT TONIGHT)."""
    n = samples(0.28)
    x = noise(n)
    t = np.linspace(0, 1, n)
    y = np.zeros(n)
    # A bank of bands swept downward, crossfaded — cheap and convincing.
    for lo, hi, w in ((4000, 9000, 1 - t), (1800, 4000, np.sin(np.pi * t)), (600, 1800, t)):
        y += bandpass(x, lo, hi) * w
    return finish(y * env(n, 0.04, 0.0, 1.0, 0.16))


def sfx_select() -> np.ndarray:
    """A confident pick (PLAYING IT, a RANK choice): a quick rising major arpeggio."""
    notes = ["C5", "E5", "G5", "C6"]
    parts = [pulse_note(nm, 0.045, duty=0.25, decay=0.02, sustain=0.8, release=0.008) for nm in notes[:-1]]
    parts.append(pulse_note(notes[-1], 0.22, duty=0.25, decay=0.1, sustain=0.3, release=0.1))
    return finish(room(np.concatenate(parts), 0.15, 0.3))


def sfx_blip() -> np.ndarray:
    """The button press. Deliberately tiny — it plays more than anything else."""
    n = samples(0.045)
    f = np.linspace(1500, 1100, n)
    return finish(triangle(f, n) * exp_decay(n, 0.012), peak=0.6)


def sfx_tick() -> np.ndarray:
    """A detent — one card passing in STACK, one letter of GAME CLEARED typing."""
    n = samples(0.02)
    return finish(bandpass(noise(n), 2500, 6500) * exp_decay(n, 0.003) + square(2200, n, 0.5) * exp_decay(n, 0.002) * 0.3, peak=0.55)


def sfx_error() -> np.ndarray:
    """Can't afford it / declined. Two low buzzes, falling — informative, not scolding."""
    a = pulse_note("E3", 0.09, duty=0.25, decay=0.02, sustain=0.8, release=0.02)
    gap = np.zeros(samples(0.03))
    b = pulse_note("C3", 0.16, duty=0.25, decay=0.05, sustain=0.6, release=0.06)
    return finish(lowpass(np.concatenate([a, gap, b]), 2500), peak=0.7)


def sfx_add() -> np.ndarray:
    """A game saved into the pile — an "item get" chime with a little echo."""
    notes = ["G5", "B5", "D6", "G6"]
    parts = [pulse_note(nm, 0.06, duty=0.5, decay=0.02, sustain=0.7, release=0.01) for nm in notes[:-1]]
    parts.append(pulse_note(notes[-1], 0.3, duty=0.5, decay=0.15, sustain=0.25, release=0.12))
    x = np.concatenate(parts) * 0.8
    return finish(room(echo(x, 0.11, 0.3, 0.4), 0.12, 0.2))


def sfx_friend() -> np.ndarray:
    """"A NEW CHALLENGER HAS ENTERED" — a friend's pile arriving."""
    buf = np.zeros(samples(1.1))
    for at, nm, ln in ((0.0, "A4", 0.1), (0.1, "A4", 0.1), (0.2, "E5", 0.1), (0.3, "A5", 0.45)):
        place(buf, pulse_note(nm, ln, duty=0.25, vibrato=0.01, decay=0.05, sustain=0.6, release=0.06), at)
        place(buf, pulse_note(nm, ln, duty=0.125, vibrato=0.0, decay=0.05, sustain=0.6, release=0.06) * 0.35, at + 0.012)
    place(buf, crash(0.25)[: samples(0.8)], 0.3)
    return finish(room(buf, 0.18, 0.4))


def sfx_powerup() -> np.ndarray:
    """PRO unlocked. The biggest effect in the app: a sweep up into a held major chord."""
    n = samples(0.5)
    t = np.arange(n) / n
    f = hz("C4") * 2 ** (t * 2)  # two octaves up
    stepped = np.round(np.log2(f / hz("C4")) * 12) / 12  # quantised like an old sound chip
    sweep = square(hz("C4") * 2 ** stepped, n, 0.25) * 0.6
    m = samples(0.9)
    chord = sum(square(hz(nm), m, 0.5) * 0.3 for nm in ("C6", "E6", "G6")) * exp_decay(m, 0.35)
    chord += triangle(hz("C4"), m) * exp_decay(m, 0.4) * 0.5
    x = np.concatenate([sweep, chord])
    place(x, crash(0.35)[: len(x) - n], 0.5)
    return finish(room(x, 0.2, 0.6))


def sfx_crt_on() -> np.ndarray:
    """A CRT powering on: the degauss thunk, a rising hum, static that settles."""
    total = samples(1.3)
    buf = np.zeros(total)
    n = samples(0.4)
    thunk = sine(55 + 40 * np.exp(-np.arange(n) / (0.05 * SR)), n) * exp_decay(n, 0.12)
    place(buf, thunk * 1.0, 0.0)
    place(buf, bandpass(noise(n), 200, 1200) * exp_decay(n, 0.04) * 0.5, 0.0)
    m = samples(1.1)
    t = np.arange(m) / m
    hum_f = 60 + 60 * t
    hum = (sine(hum_f, m) * 0.5 + sine(hum_f * 2, m) * 0.25) * np.sin(np.pi * np.clip(t * 1.2, 0, 1)) * 0.35
    place(buf, hum, 0.1)
    static = highpass(noise(m), 3000) * (np.exp(-t * 4)) * 0.35
    place(buf, static, 0.12)
    return finish(buf, fade_out=0.15)


# ───────────────────────────── music ─────────────────────────────

def lead(duty=0.5, vol=0.34, vibrato=0.006):
    return lambda note, secs: pulse_note(note, secs * 0.92, duty=duty, vol=vol, vibrato=vibrato,
                                         decay=0.08, sustain=0.65, release=0.04)


def music_title() -> np.ndarray:
    """Attract mode, for the cold open. Bright, 132 bpm, C major, a 16-bar loop."""
    tr = Track(132, 64, loop=True)
    progression = ["C", "Am", "F", "G", "C", "Am", ("F", "G"), "C",
                   "F", "G", "Em", "Am", "F", "G", "C", "G"]
    for bar, chord in enumerate(progression):
        b = bar * 4
        halves = chord if isinstance(chord, tuple) else (chord, chord)
        for h, ch in enumerate(halves):
            arp(tr, b + h * 2, ch, 4, beats=2, vol=0.12)
            bass(tr, b + h * 2, CHORDS[ch][0], octave=2, beats=2, vol=0.5)
        drums(tr, b, vol=0.9)
    phrase_a = [
        ("E5", .5), ("G5", .5), ("C6", 1), ("B5", .5), ("G5", .5), ("E5", 1),
        ("A5", 1.5), ("G5", .5), ("E5", 1), ("C5", 1),
        ("F5", .5), ("A5", .5), ("C6", 1), ("A5", .5), ("F5", .5), ("A5", 1),
        ("G5", 1.5), ("F5", .5), ("E5", 1), ("D5", 1),
        ("E5", .5), ("G5", .5), ("C6", 1), ("D6", .5), ("C6", .5), ("G5", 1),
        ("A5", 1), ("C6", 1), ("E6", 1.5), ("D6", .5),
        ("C6", 1), ("A5", 1), ("B5", 1), ("D6", 1),
        ("C6", 3), (None, 1),
    ]
    phrase_b = [
        ("A5", .5), ("C6", .5), ("F6", 1), ("E6", .5), ("D6", .5), ("C6", 1),
        ("B5", .5), ("D6", .5), ("G6", 1), ("F6", .5), ("E6", .5), ("D6", 1),
        ("E6", 1), ("B5", 1), ("G5", 1), ("B5", 1),
        ("C6", 1.5), ("B5", .5), ("A5", 2),
        ("F5", .5), ("A5", .5), ("C6", .5), ("F6", .5), ("E6", 1), ("C6", 1),
        ("D6", .5), ("B5", .5), ("G5", .5), ("B5", .5), ("D6", 1), ("G6", 1),
        ("E6", 1), ("D6", .5), ("C6", .5), ("D6", 1), ("E6", 1),
        ("D6", 2), ("B5", 1), ("G5", 1),
    ]
    b = tr.melody(0, phrase_a, lead())
    tr.melody(b, phrase_b, lead())
    # A quiet echo voice an octave down gives the lead body without a second melody to learn.
    b = tr.melody(0.01, [(n and n[:-1] + str(int(n[-1]) - 1), l) for n, l in phrase_a], lead(0.25, 0.1, 0))
    tr.melody(b, [(n and n[:-1] + str(int(n[-1]) - 1), l) for n, l in phrase_b], lead(0.25, 0.1, 0))
    return master(tr.buf, loop=True, lp=6000)


def music_continue() -> np.ndarray:
    """The CONTINUE? screen: minor, ticking, patient. An 8-bar loop at 112 bpm."""
    tr = Track(112, 32, loop=True)
    progression = ["Am", "F", "G", "E", "Am", "F", "G", "E"]
    for bar, ch in enumerate(progression):
        b = bar * 4
        arp(tr, b, ch, 4, vol=0.13, pattern=(0, 1, 2, 3, 2, 1))
        bass(tr, b, CHORDS[ch][0], octave=2, vol=0.5, style="pulse")
        # The clock: a hat on every beat, accented on one — the countdown without the number.
        for beat in range(4):
            tr.add(b + beat, hat(0.3 if beat == 0 else 0.18, open_=beat == 0))
        tr.add(b, kick(0.55))
    melody = [("E5", 4), ("F5", 4), ("D5", 4), ("G#5", 4),
              ("A5", 2), ("G5", 2), ("F5", 2), ("E5", 2), ("D5", 2), ("B4", 2), ("G#4", 2), ("B4", 2)]
    tr.melody(0, melody, lead(duty=0.25, vol=0.22, vibrato=0.01))
    return master(tr.buf, loop=True, lp=6000)


def music_shop() -> np.ndarray:
    """The GO PRO counter: a laid-back shopkeeper loop, 96 bpm, jazzy sevenths, swung hats."""
    tr = Track(96, 32, loop=True)
    progression = ["Fmaj7", "Dm7", "Gm7", "C7", "Fmaj7", "Dm7", "Gm7", "C7"]
    walk = {"Fmaj7": ["F2", "A2", "C3", "E3"], "Dm7": ["D2", "F2", "A2", "C3"],
            "Gm7": ["G2", "Bb2", "D3", "F3"], "C7": ["C3", "Bb2", "G2", "E2"]}
    for bar, ch in enumerate(progression):
        b = bar * 4
        for i, nm in enumerate(walk[ch]):
            tr.add(b + i, tri_note(nm, tr.seconds(1) * 0.85, vol=0.55))
        # Comped chord stabs on the off-beats of 2 and 4.
        for stab in (1.66, 3.66):
            chord = sum(pulse_note(f"{t}4", tr.seconds(0.3), duty=0.25, vol=0.07, decay=0.05, sustain=0.4)
                        for t in CHORDS[ch])
            tr.add(b + stab, lowpass(chord, 3000))
        for beat in range(4):  # swung eighths
            tr.add(b + beat, hat(0.14))
            tr.add(b + beat + 0.66, hat(0.08))
        tr.add(b, kick(0.4))
        tr.add(b + 2.5, kick(0.25))
    melody = [
        ("A5", .66), ("C6", .34), ("E6", 1), ("D6", 1), ("C6", 1),
        ("A5", 1.5), ("F5", .5), ("A5", 2),
        ("Bb5", .66), ("D6", .34), ("F6", 1), ("E6", .66), ("D6", .34), ("Bb5", 1),
        ("C6", 3), (None, 1),
        ("A5", .66), ("C6", .34), ("E6", 1), ("G6", 1), ("F6", 1),
        ("D6", 1.5), ("C6", .5), ("A5", 2),
        ("G5", .66), ("Bb5", .34), ("D6", 1), ("C6", .66), ("Bb5", .34), ("G5", 1),
        ("F5", 2), (None, 2),
    ]
    tr.melody(0, melody, lead(duty=0.25, vol=0.2, vibrato=0.008))
    return master(tr.buf, loop=True, lp=6000)


def music_victory() -> np.ndarray:
    """GAME CLEARED. A fanfare that lands with the credits, then a gentle outro. Plays once."""
    tr = Track(150, 26, loop=False)
    fanfare = [("C5", .25), ("E5", .25), ("G5", .25), ("C6", .25),
               ("E6", 1), ("C6", .5), ("D6", .5), ("E6", .5), ("G6", 1.5),
               ("F6", .5), ("E6", .5), ("D6", .5), ("C6", .5), ("D6", 1), ("G5", 1),
               ("C6", 3)]
    end = tr.melody(0, fanfare, lead(duty=0.5, vol=0.4, vibrato=0.008))
    tr.melody(0.02, [(n and {"C5": "G4", "E5": "C5", "G5": "E5", "C6": "G5", "E6": "C6", "D6": "B5",
                             "G6": "E6", "F6": "A5"}[n], l) for n, l in fanfare], lead(duty=0.25, vol=0.18, vibrato=0))
    # Harmony and drive under the fanfare.
    for b, ch in ((1, "C"), (3, "C"), (5, "F"), (7, "G")):
        bass(tr, b, CHORDS[ch][0], octave=2, beats=2, vol=0.5)
        drums(tr, b, beats=2, kick_on=(0,), snare_on=(1,), hats=0.5, vol=0.8)
    for i in range(8):  # snare roll into the landing
        tr.add(8 + i * 0.125, snare(0.18 + i * 0.03))
    tr.add(end - 3, crash(0.45))
    tr.add(end - 3, kick(1.0))
    tr.add(end - 3, tri_note("C2", tr.seconds(3), vol=0.6))
    for t in CHORDS["C"]:
        tr.add(end - 3, pulse_note(f"{t}4", tr.seconds(3), duty=0.125, vol=0.1, decay=0.4, sustain=0.5, release=0.6))
    # Outro: soft arps over the credits, thinning out.
    for i, ch in enumerate(["C", "Am", "F", "G", "C"]):
        b = end + i * 2
        fade = 1 - i * 0.16
        arp(tr, b, ch, 5, beats=2, step=0.25, vol=0.1 * fade, duty=0.25, pattern=(0, 1, 2, 3))
        tr.add(b, tri_note(f"{CHORDS[ch][0]}2", tr.seconds(2), vol=0.4 * fade))
    out = room(tr.buf, 0.2, 1.0)
    return master(out[: samples(tr.seconds(end + 10) + 1.2)], loop=False, lp=6000, fade_out=1.2)


# ───────────────────────────── mastering ─────────────────────────────

MUSIC_RMS_DBFS = -16.0


def _circular(fn, x: np.ndarray) -> np.ndarray:
    """Applies a filter to a loop as if it had always been looping, so the seam carries the
    filter's state across instead of clicking: run it over three copies, keep the middle."""
    n = len(x)
    return fn(np.tile(x, 3))[n: 2 * n]


def master(x: np.ndarray, loop: bool, lp: float | None = None, fade_out: float = 0.0005) -> np.ndarray:
    """Every music track ends here, so all three packs sit at the same loudness.

    Loudness is matched by RMS, not peak: the first build peak-normalised, which made the dense
    square-wave arcade tracks far louder than their meters said (the first device test put 50%
    phone volume at "sounds like 90%"). With RMS matched, switching packs never jumps the volume,
    and the in-app level decides how loud all of them are.
    """
    if lp:
        x = _circular(lambda y: lowpass(y, lp), x) if loop else lowpass(x, lp)
    x = x - np.mean(x)
    x = x * (10 ** (MUSIC_RMS_DBFS / 20) / (np.sqrt(np.mean(x ** 2)) + 1e-12))
    ceiling = 0.85
    x = ceiling * np.tanh(x / ceiling)  # a soft ceiling, never a hard clip
    if not loop:
        fo, fi = samples(fade_out), samples(0.002)
        x[-fo:] *= np.linspace(1, 0, fo)
        x[:fi] *= np.linspace(0, 1, fi)
    return x


def loop_room(x: np.ndarray, mix: float, tail: float = 0.8) -> np.ndarray:
    """[room] for a loop: the reverb tail of the last bar rings into the first."""
    return _circular(lambda y: room(y, mix, tail)[: len(y)], x)


def up(note: str, octaves: int = 1) -> str:
    return note[:-1] + str(int(note[-1]) + octaves)


# ───────────────────────────── softer instruments ─────────────────────────────

def saw(freq, n: int) -> np.ndarray:
    t, dt = phase(freq, n)
    return 2 * t - 1 - _polyblep(t, dt)


def epiano(note: str, seconds: float, vol=1.0, decay=1.4) -> np.ndarray:
    """A Rhodes-ish electric piano: two-operator FM whose brightness fades as the note does,
    with a slow tremolo. Nothing above a few kHz — the opposite of a square wave."""
    n = samples(seconds)
    t = np.arange(n) / SR
    f = hz(note)
    index = 1.4 * np.exp(-t / 0.35)
    tone = np.sin(2 * np.pi * f * t + index * np.sin(2 * np.pi * f * t))
    tone += 0.12 * np.sin(2 * np.pi * 2 * f * t) * np.exp(-t / 0.2)
    amp = np.exp(-t / decay) * (1 + 0.08 * np.sin(2 * np.pi * 4.2 * t))
    return tone * amp * env(n, 0.004, 0, 1, 0.08) * vol


def epiano_chord(notes, seconds: float, vol=0.2, strum=0.012, decay=1.4) -> np.ndarray:
    out = np.zeros(samples(seconds + strum * len(notes)))
    for i, nm in enumerate(notes):
        place(out, epiano(nm, seconds, vol, decay), i * strum)
    return out


def bell(note: str, seconds: float, vol=1.0) -> np.ndarray:
    """A soft glockenspiel: a sine with two inharmonic partials that die first."""
    n = samples(seconds)
    t = np.arange(n) / SR
    f = hz(note)
    x = np.sin(2 * np.pi * f * t) * np.exp(-t / 0.9)
    x += 0.25 * np.sin(2 * np.pi * 2.76 * f * t) * np.exp(-t / 0.25)
    x += 0.08 * np.sin(2 * np.pi * 5.4 * f * t) * np.exp(-t / 0.08)
    return x * env(n, 0.002, 0, 1, 0.05) * vol


def pad(notes, seconds: float, vol=0.1, attack=0.6, release=0.8, bright=1400, kind="soft") -> np.ndarray:
    """A sustained chord. "soft" is detuned sine+triangle (warm, no edge); "saw" is a supersaw
    for the synthwave pack, filtered so it glows rather than buzzes."""
    n = samples(seconds)
    out = np.zeros(n)
    for nm in notes:
        f = hz(nm)
        for detune in (0.997, 1.0, 1.003):
            if kind == "saw":
                out += saw(f * detune, n)
            else:
                out += sine(f * detune, n) * 0.7 + triangle(f * detune, n) * 0.3
    out = lowpass(out / (3 * len(notes)), bright)
    return out * env(n, attack, 0, 1, release) * vol


def sub(note: str, seconds: float, vol=0.5) -> np.ndarray:
    n = samples(seconds)
    f = hz(note)
    return (sine(f, n) + 0.15 * sine(2 * f, n)) * env(n, 0.01, 0, 1, 0.06) * vol


def soft_kick(vol=1.0) -> np.ndarray:
    n = samples(0.25)
    f = 42 + 60 * np.exp(-np.arange(n) / (0.04 * SR))
    return sine(f, n) * exp_decay(n, 0.09) * vol


def brush(vol=1.0) -> np.ndarray:
    """A brushed snare: band-limited noise, no crack, nothing above 5 kHz."""
    n = samples(0.22)
    return bandpass(noise(n), 500, 4500) * env(n, 0.012, 0.05, 0.35, 0.12) * vol


def gated_snare(vol=1.0) -> np.ndarray:
    """The 80s snare: a fat hit with a big room, cut off short."""
    n = samples(0.35)
    body = triangle(180, n) * exp_decay(n, 0.04) * 0.6
    rattle = bandpass(noise(n), 900, 6000) * exp_decay(n, 0.12)
    x = room(body + rattle, 0.45, 0.0)[:n]
    return x * env(n, 0.001, 0, 1, 0.1) * vol


def synth_lead(note: str, seconds: float, vol=0.3, cutoff=3200) -> np.ndarray:
    n = samples(seconds)
    t = np.arange(n) / SR
    f = hz(note) * (1 + 0.006 * np.clip(t / 0.3, 0, 1) * np.sin(2 * np.pi * 5.2 * t))
    x = saw(f, n) * 0.6 + square(f * 1.004, n, 0.5) * 0.4
    return lowpass(x, cutoff) * env(n, 0.01, 0.12, 0.7, 0.08) * vol


def synth_bass(note: str, seconds: float, vol=0.5) -> np.ndarray:
    n = samples(seconds)
    x = saw(hz(note), n) * 0.7 + sine(hz(note), n) * 0.5
    return lowpass(x, 650) * env(n, 0.004, 0.08, 0.6, 0.03) * vol


def pluck(note: str, seconds: float, vol=0.12, cutoff=2600) -> np.ndarray:
    n = samples(seconds)
    x = saw(hz(note), n) * exp_decay(n, 0.12)
    return lowpass(x, cutoff) * env(n, 0.002, 0, 1, 0.02) * vol


# ───────────────────────────── AFTER HOURS (calm) ─────────────────────────────
# Lo-fi late night: electric piano, warm pads, sub bass, brushes, a little bell. Slow tempos,
# sevenths and ninths, nothing bright. For people who want the app to feel like a quiet room
# rather than an arcade floor.

def ah_title() -> np.ndarray:
    tr = Track(74, 32, loop=True)
    chords = [["F3", "A3", "C4", "E4", "G4"], ["E3", "G3", "B3", "D4"],
              ["D3", "F3", "A3", "C4", "E4"], ["C3", "E3", "G3", "B3", "D4"]] * 2
    roots = ["F2", "E2", "D2", "C2"] * 2
    for bar, (ch, root) in enumerate(zip(chords, roots)):
        b = bar * 4
        tr.add(b, epiano_chord(ch, tr.seconds(2.2), vol=0.16))
        tr.add(b + 2.5, epiano_chord(ch[1:], tr.seconds(1.4), vol=0.1))
        tr.add(b, pad([up(c) for c in ch[:3]], tr.seconds(4), vol=0.05))
        tr.add(b, sub(root, tr.seconds(2.3)))
        tr.add(b + 2.5, sub(root, tr.seconds(1.3), 0.4))
        tr.add(b, soft_kick(0.8))
        tr.add(b + 2.5, soft_kick(0.55))
        tr.add(b + 1.05, brush(0.35))  # laid back: a hair behind the beat
        tr.add(b + 3.05, brush(0.35))
    melody = [(None, 2), ("C5", .5), ("E5", .5), ("G5", 1),
              (None, 4),
              (None, 2), ("A4", .5), ("C5", .5), ("E5", 1),
              (None, 4),
              ("E5", 1), ("G5", 1), ("A5", 2),
              ("G5", 1.5), ("E5", .5), ("D5", 2),
              ("F5", 1), ("A5", 1), ("C6", 1), ("A5", 1),
              ("G5", 3), (None, 1)]
    tr.melody(0, melody, lambda nm, secs: bell(nm, secs + 0.8, 0.22))
    return master(loop_room(tr.buf, 0.22), loop=True, lp=5000)


def ah_continue() -> np.ndarray:
    tr = Track(66, 32, loop=True)
    chords = [["A3", "C4", "E4", "G4", "B4"], ["F3", "A3", "C4", "E4"],
              ["C3", "G3", "B3", "E4"], ["G3", "B3", "D4", "E4"]] * 2
    roots = ["A1", "F1", "C2", "G1"] * 2
    for bar, (ch, root) in enumerate(zip(chords, roots)):
        b = bar * 4
        tr.add(b, pad(ch, tr.seconds(4.4), vol=0.09, attack=1.0, release=1.2))
        tr.add(b, sub(root, tr.seconds(4), 0.45))
        for i in range(8):  # a slow rising arpeggio: the patience the screen asks for
            tr.add(b + i * 0.5, epiano(ch[i % len(ch)], tr.seconds(1.2), 0.08, decay=0.7))
    melody = [(None, 16), ("E5", 2), ("D5", 2), ("C5", 4), ("B4", 2), ("C5", 2), ("D5", 4)]
    tr.melody(0, melody, lambda nm, secs: bell(nm, secs + 1.0, 0.18))
    return master(loop_room(tr.buf, 0.25), loop=True, lp=4500)


def ah_shop() -> np.ndarray:
    tr = Track(84, 32, loop=True)
    chords = [["D3", "F3", "A3", "C4", "E4"], ["G3", "B3", "D4", "F4", "A4"],
              ["C3", "E3", "G3", "B3", "D4"], ["A2", "C3", "E3", "G3", "B3"]] * 2
    walks = [["D2", "F2", "A2", "C3"], ["G2", "B2", "D3", "F3"],
             ["C2", "E2", "G2", "B2"], ["A2", "G2", "E2", "C2"]] * 2
    for bar, (ch, walk) in enumerate(zip(chords, walks)):
        b = bar * 4
        for i, nm in enumerate(walk):
            tr.add(b + i, sub(nm, tr.seconds(0.9), 0.45))
        for stab in (0.66, 2.66):  # swung comping
            tr.add(b + stab, epiano_chord(ch, tr.seconds(0.9), vol=0.1, decay=0.8))
        tr.add(b, soft_kick(0.5))
        for beat in range(4):
            tr.add(b + beat, brush(0.18))
            tr.add(b + beat + 0.66, brush(0.1))
    melody = [("A5", .66), ("F5", .34), ("E5", 1), ("D5", 2),
              ("B4", .66), ("D5", .34), ("F5", 1), ("A5", 2),
              ("G5", 1), ("E5", 1), ("D5", .66), ("C5", .34), ("B4", 1),
              ("C5", 3), (None, 1),
              ("A5", .66), ("C6", .34), ("A5", 1), ("F5", 2),
              ("G5", .66), ("A5", .34), ("B5", 1), ("D6", 2),
              ("C6", 1), ("B5", 1), ("G5", 1), ("E5", 1),
              ("D5", 2), (None, 2)]
    tr.melody(0, melody, lambda nm, secs: epiano(nm, secs + 0.3, 0.2, decay=0.6))
    return master(loop_room(tr.buf, 0.18), loop=True, lp=5000)


def ah_victory() -> np.ndarray:
    tr = Track(80, 16, loop=False)
    for i, nm in enumerate(["C3", "G3", "C4", "E4", "G4", "B4", "D5", "E5"]):  # a harp sweep
        tr.add(i * 0.25, epiano(nm, tr.seconds(6 - i * 0.25), 0.12, decay=2.0))
    tr.add(0, pad(["C4", "E4", "G4", "B4"], tr.seconds(6), vol=0.08, attack=1.2, release=1.5))
    tr.add(0, sub("C2", tr.seconds(6), 0.45))
    tr.add(6, pad(["F3", "A3", "C4", "E4"], tr.seconds(2.2), vol=0.08, attack=0.4, release=0.8))
    tr.add(6, sub("F2", tr.seconds(2), 0.4))
    tr.add(8, pad(["C4", "E4", "G4", "B4", "D5"], tr.seconds(6), vol=0.09, attack=0.6, release=2.0))
    tr.add(8, epiano_chord(["C3", "G3", "E4", "B4", "D5"], tr.seconds(5), vol=0.12, decay=2.5))
    tr.add(8, sub("C2", tr.seconds(5), 0.45))
    melody = [(None, 2), ("G5", 1), ("E5", .5), ("G5", .5), ("C6", 2),
              ("B5", 1), ("A5", 1), ("E6", 4)]
    tr.melody(0, melody, lambda nm, secs: bell(nm, secs + 1.2, 0.28))
    out = room(tr.buf, 0.3, 1.5)
    return master(out[: samples(tr.seconds(16) + 1.5)], loop=False, lp=5000, fade_out=2.0)


# ───────────────────────────── NEON DRIVE (synthwave) ─────────────────────────────
# 1980s night-drive synthwave: driving saw bass, wide filtered supersaw pads, a gated snare in a
# big room, a singing lead. Between the other two packs — as retro as the cabinet, but warm and
# wide instead of chirpy.

def nd_title() -> np.ndarray:
    tr = Track(104, 32, loop=True)
    chords = [["A3", "C4", "E4"], ["F3", "A3", "C4"], ["C4", "E4", "G4"], ["G3", "B3", "D4"]] * 2
    roots = ["A1", "F1", "C2", "G1"] * 2
    for bar, (ch, root) in enumerate(zip(chords, roots)):
        b = bar * 4
        tr.add(b, pad(ch, tr.seconds(4.2), vol=0.11, attack=0.25, release=0.3, bright=2200, kind="saw"))
        for i in range(8):
            tr.add(b + i * 0.5, synth_bass(root if i % 2 == 0 else up(root), tr.seconds(0.45), 0.4))
        for i in range(16):
            tr.add(b + i * 0.25, pluck(up(ch[i % 3]), tr.seconds(0.22), 0.05))
        tr.add(b, kick(0.8))
        tr.add(b + 2, kick(0.8))
        tr.add(b + 1, gated_snare(0.4))
        tr.add(b + 3, gated_snare(0.4))
        for i in range(8):
            tr.add(b + i * 0.5, lowpass(hat(0.25), 9000))
    melody = [(None, 16),
              ("E5", 1.5), ("D5", .5), ("C5", 1), ("D5", 1),
              ("C5", 1.5), ("A4", .5), ("C5", 1), ("F5", 1),
              ("E5", 1.5), ("D5", .5), ("C5", 1), ("G5", 1),
              ("D5", 3), (None, 1)]
    tr.melody(0, melody, lambda nm, secs: synth_lead(nm, secs * 0.95, 0.22))
    return master(loop_room(tr.buf, 0.2), loop=True, lp=7000)


def nd_continue() -> np.ndarray:
    tr = Track(96, 32, loop=True)
    chords = [["E3", "G3", "B3"], ["C3", "E3", "G3"], ["D3", "F#3", "A3"], ["B2", "D#3", "F#3"]] * 2
    roots = ["E1", "C2", "D2", "B1"] * 2
    for bar, (ch, root) in enumerate(zip(chords, roots)):
        b = bar * 4
        tr.add(b, pad([up(c) for c in ch], tr.seconds(4.2), vol=0.1, attack=0.5, release=0.4, bright=1800, kind="saw"))
        for i in range(8):
            tr.add(b + i * 0.5, synth_bass(root, tr.seconds(0.42), 0.38))
        tr.add(b, kick(0.7))
        for beat in range(4):  # the clock, softer than the arcade one
            tr.add(b + beat, lowpass(hat(0.35 if beat == 0 else 0.22), 8000))
    melody = [("B4", 4), ("C5", 4), ("A4", 4), ("D#5", 4),
              ("E5", 2), ("D5", 2), ("C5", 2), ("G4", 2), ("A4", 2), ("F#4", 2), ("D#4", 4)]
    tr.melody(0, melody, lambda nm, secs: synth_lead(nm, secs * 0.95, 0.16, cutoff=2200))
    return master(loop_room(tr.buf, 0.22), loop=True, lp=6500)


def nd_shop() -> np.ndarray:
    tr = Track(92, 32, loop=True)
    chords = [["C4", "E4", "G4", "B4"], ["A3", "C4", "E4", "G4"],
              ["F3", "A3", "C4", "E4"], ["G3", "B3", "D4", "E4"]] * 2
    roots = ["C2", "A1", "F1", "G1"] * 2
    for bar, (ch, root) in enumerate(zip(chords, roots)):
        b = bar * 4
        tr.add(b, pad(ch, tr.seconds(4.2), vol=0.08, attack=0.3, release=0.4, bright=1600, kind="saw"))
        for off in (0, 0.75, 1.5, 2.5, 3.0):  # a syncopated, funky bass
            tr.add(b + off, synth_bass(up(root) if off == 1.5 else root, tr.seconds(0.4), 0.38))
        tr.add(b, kick(0.6))
        tr.add(b + 2.5, kick(0.4))
        tr.add(b + 1, gated_snare(0.28))
        tr.add(b + 3, gated_snare(0.28))
    melody = [("G4", .5), ("C5", .5), ("E5", 1), ("D5", 1), ("C5", 1),
              ("E5", 2), ("A4", 2),
              ("F5", .5), ("E5", .5), ("C5", 1), ("A4", 2),
              ("G4", 3), (None, 1),
              ("G4", .5), ("C5", .5), ("E5", 1), ("G5", 1), ("E5", 1),
              ("C5", 2), ("A4", 2),
              ("F5", .5), ("E5", .5), ("C5", 1), ("A4", 2),
              ("D5", 2), ("B4", 2)]
    tr.melody(0, melody, lambda nm, secs: synth_lead(nm, secs * 0.9, 0.16, cutoff=2400))
    return master(loop_room(tr.buf, 0.2), loop=True, lp=6500)


def nd_victory() -> np.ndarray:
    tr = Track(110, 20, loop=False)
    for i in range(8):  # the build
        tr.add(i * 0.25, gated_snare(0.12 + i * 0.04))
    tr.add(0, pad(["A3", "C4", "E4"], tr.seconds(2), vol=0.08, attack=1.2, release=0.1, bright=1500, kind="saw"))
    lead = [(None, 2), ("C5", .5), ("E5", .5), ("G5", .5), ("C6", .5),
            ("E6", 2), ("D6", 1), ("C6", 1), ("D6", 1.5), ("B5", .5), ("G5", 2), ("C6", 6)]
    tr.melody(0, lead, lambda nm, secs: synth_lead(nm, secs * 0.95, 0.26, cutoff=3800))
    for b, ch, root, ln in ((2, ["C4", "E4", "G4"], "C2", 4), (6, ["G3", "B3", "D4"], "G1", 4),
                            (10, ["C4", "E4", "G4", "C5"], "C2", 6)):
        tr.add(b, pad(ch, tr.seconds(ln), vol=0.12, attack=0.05, release=1.2, bright=2600, kind="saw"))
        for i in range(int(ln * 2)):
            tr.add(b + i * 0.5, synth_bass(root, tr.seconds(0.45), 0.36 if i < ln * 2 - 2 else 0.2))
        tr.add(b, kick(0.9))
        tr.add(b, crash(0.2))
        tr.add(b + 1, gated_snare(0.35))
        tr.add(b + 3, gated_snare(0.35))
    out = room(tr.buf, 0.25, 1.5)
    return master(out[: samples(tr.seconds(16) + 1.5)], loop=False, lp=7000, fade_out=2.0)


if __name__ == "__main__":
    for name, fn in [
        ("sfx_coin", sfx_coin), ("sfx_coin_drop", sfx_coin_drop), ("sfx_lever", sfx_lever),
        ("sfx_deal", sfx_deal), ("sfx_flip", sfx_flip), ("sfx_whoosh", sfx_whoosh),
        ("sfx_select", sfx_select), ("sfx_blip", sfx_blip), ("sfx_tick", sfx_tick),
        ("sfx_error", sfx_error), ("sfx_add", sfx_add), ("sfx_friend", sfx_friend),
        ("sfx_powerup", sfx_powerup), ("sfx_crt_on", sfx_crt_on),
        # Three packs of four slots, named music_<pack>_<slot> to match MusicPack in the app.
        ("music_arcade_title", music_title), ("music_arcade_continue", music_continue),
        ("music_arcade_shop", music_shop), ("music_arcade_victory", music_victory),
        ("music_afterhours_title", ah_title), ("music_afterhours_continue", ah_continue),
        ("music_afterhours_shop", ah_shop), ("music_afterhours_victory", ah_victory),
        ("music_neondrive_title", nd_title), ("music_neondrive_continue", nd_continue),
        ("music_neondrive_shop", nd_shop), ("music_neondrive_victory", nd_victory),
    ]:
        write(name, fn())
